#!/usr/bin/env node
/**
 * Point the site at your Google Form so student progress lands in your Sheet.
 *
 *   npm run link-form -- "https://docs.google.com/forms/d/e/FORM_ID/viewform"
 *   npm run link-form -- --off        turn reporting back off
 *
 * Your form needs five short-answer questions, in any order. The titles just
 * have to CONTAIN these words (case doesn't matter):
 *
 *     Student        who it is
 *     Lesson         which lesson
 *     Status         done or opened
 *     Minutes        active time on that lesson
 *     Total          their total minutes so far
 *
 * This script reads the form, works out Google's internal field ids for you,
 * and writes them to src/data/reporting.json. You never have to look at them.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const FILE = join(root, 'src', 'data', 'reporting.json');

const arg = process.argv.slice(2).find((a) => !a.startsWith('--'));
if (process.argv.includes('--off')) {
  writeFileSync(FILE, JSON.stringify({
    '//': 'Set up with: npm run link-form -- <your Google Form URL>. Empty formUrl = reporting off.',
    formUrl: '', fields: {},
  }, null, 2) + '\n');
  console.log('\n  Reporting turned off. Students send nothing.\n');
  process.exit(0);
}

if (!arg) {
  console.error('\n  Usage: npm run link-form -- "https://docs.google.com/forms/d/e/…/viewform"\n');
  process.exit(1);
}

const m = arg.match(/\/forms\/d\/e\/([\w-]+)/);
if (!m) {
  console.error('\n  That does not look like a Google Form link. It should contain /forms/d/e/…\n');
  process.exit(1);
}
const formId = m[1];
const viewUrl = `https://docs.google.com/forms/d/e/${formId}/viewform`;

console.log('\n  Reading your form…');
const res = await fetch(viewUrl);
if (!res.ok) {
  console.error(`  Could not open the form (HTTP ${res.status}). Is it accepting responses?\n`);
  process.exit(1);
}
const html = await res.text();

/* Google embeds the question list as a JSON blob. Each entry looks roughly like
   [null,"Question title",null,0,[[ENTRY_ID,...]]] — pull those pairs out. */
const found = [];
for (const chunk of html.matchAll(/\[null,"((?:[^"\\]|\\.)*)",[^\]]*?,\d+,\[\[(\d{6,})/g)) {
  found.push({ title: JSON.parse(`"${chunk[1]}"`), entry: `entry.${chunk[2]}` });
}

if (!found.length) {
  console.error('  Could not find any questions. Make sure the form is open to responses');
  console.error('  and uses short-answer questions, then try again.\n');
  process.exit(1);
}

console.log(`  Found ${found.length} question(s):`);
for (const f of found) console.log(`    "${f.title}"  ->  ${f.entry}`);

const want = ['student', 'lesson', 'status', 'minutes', 'total'];
const fields = {};
const missing = [];
for (const key of want) {
  const hit = found.find((f) => f.title.toLowerCase().includes(key));
  if (hit) fields[key] = hit.entry;
  else missing.push(key);
}

if (missing.length) {
  console.error(`\n  These questions are missing (the title must contain the word):`);
  for (const k of missing) console.error(`    ${k}`);
  console.error('\n  Add them as short-answer questions and run this again.\n');
  process.exit(1);
}

writeFileSync(FILE, JSON.stringify({
  '//': 'Generated by npm run link-form. Student progress posts to this form.',
  formUrl: `https://docs.google.com/forms/d/e/${formId}/formResponse`,
  fields,
}, null, 2) + '\n');

console.log('\n  Linked. Students will now report progress to that form.');
console.log('  Run `npm run publish` to put it live.\n');
