#!/usr/bin/env node
/**
 * Build the site's course data from content/course.json.
 *
 *   npm run seal
 *
 * Writes two things:
 *   src/data/curriculum.ts   the PUBLIC half — units, lesson titles, blurbs.
 *                            Committed. Anyone can read it. Good for search engines.
 *   public/course.enc.json   the PRIVATE half — video URLs, slides, code, wiring,
 *                            materials, "what you'll learn". Encrypted. Committed.
 *
 * content/course.json itself is gitignored, because the repo is public and those
 * YouTube videos are unlisted — the URL *is* the secret.
 *
 * Lost content/course.json? `npm run unseal` rebuilds it from the encrypted file,
 * as long as you still have .course-key.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateCourseKey, encryptJson } from './crypto.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const SRC = join(root, 'content', 'course.json');
const KEY_FILE = join(root, '.course-key');
const ENC = join(root, 'public', 'course.enc.json');
const TS = join(root, 'src', 'data', 'curriculum.ts');
const ROSTER = join(root, 'src', 'data', 'roster.json');

if (!existsSync(SRC)) {
  console.error(`\n  content/course.json is missing.\n  If you have .course-key, run:  npm run unseal\n`);
  process.exit(1);
}

let courseKey;
if (existsSync(KEY_FILE)) courseKey = readFileSync(KEY_FILE, 'utf8').trim();
else {
  courseKey = await generateCourseKey();
  writeFileSync(KEY_FILE, courseKey + '\n');
  console.log('\n  Created .course-key — this is the master key. Back it up.\n');
}

const course = JSON.parse(readFileSync(SRC, 'utf8'));
const J = JSON.stringify;

/* ---------- split public / private ------------------------------------ */
const secret = {};
for (const u of course.units)
  for (const l of u.lessons)
    secret[l.slug] = {
      video: l.video || '',
      resources: l.resources || [],
      materials: l.materials || [],
      learn: l.learn || [],
    };

writeFileSync(ENC, J(await encryptJson(courseKey, secret)));

/* ---------- generate the public curriculum ---------------------------- */
const CAPSTONES = [
  ['A', 'RC Car', 'Build a two-wheel-drive car from a bare chassis, then drive it around your house.',
   ['DC motors', 'L298N H-bridge', 'Chassis build', 'Speed control']],
  ['B', 'Tic-Tac-Toe', 'An LED board, buttons, and an opponent you wrote yourself.',
   ['Arrays & game state', 'Win detection', 'Simple AI', 'Big-board wiring']],
  ['C', 'Laser Harp', 'Invisible strings made of light. Wave your hand through a beam and it plays a note.',
   ['Lasers & photoresistors', 'Calibration', 'Tone generation']],
  ['D', 'Crack the Vault', 'A keypad-locked vault with a servo bolt, an alarm, and a combination only you know.',
   ['Keypad input', 'Servo lock', 'State machines']],
  ['E', 'Sentry Turret', 'A pan-tilt turret that scans the room, locks onto a target and fires.',
   ['Pan-tilt servos', 'Ultrasonic ranging', 'Target tracking']],
];
const projCount = (L) =>
  course.units.flatMap((u) => u.lessons).filter((l) => l.project === L).length;

const out = [];
out.push(`// GENERATED by \`npm run seal\` from content/course.json — do not edit by hand.
//
// This is the PUBLIC half of the course: the outline. Video URLs, slides, code,
// wiring, materials and learning goals are NOT here — they live encrypted in
// public/course.enc.json and are decrypted in the browser once a student signs in.

import type { Lesson, Unit, Capstone } from '@/lib/types';

const rawUnits: (Omit<Unit, 'lessons'> & { lessons: Omit<Lesson, 'unitId'>[] })[] = [`);
for (const u of course.units) {
  out.push(`  {
    id: ${J(u.id)}, num: ${J(u.num)}, title: ${J(u.title)}, emoji: ${J(u.emoji)},
    tagline: ${J(u.tagline)}, blurb: ${J(u.blurb)}, accent: ${J(u.accent)},
    lessons: [`);
  for (const l of u.lessons) {
    const extra =
      (l.optional ? ' optional: true,' : '') +
      (l.project ? ` project: ${J(l.project)},` : '') +
      (l.tour ? ' tour: true,' : '');
    out.push(
      `      { slug: ${J(l.slug)}, id: ${J(l.id)}, title: ${J(l.title)}, blurb: ${J(l.blurb)},` +
      ` hasVideo: ${Boolean(l.video)},${extra} },`,
    );
  }
  out.push('    ],\n  },');
}
out.push('];\n');
out.push(`export const capstones: Capstone[] = [`);
for (const [letter, name, blurb, skills] of CAPSTONES)
  out.push(`  { letter: ${J(letter)}, name: ${J(name)}, blurb: ${J(blurb)}, skills: ${J(skills)}, lessonCount: ${projCount(letter)} },`);
out.push('];\n');
out.push(`export const units: Unit[] = rawUnits.map((u) => ({
  ...u,
  lessons: u.lessons.map((l) => ({ ...l, unitId: u.id })),
}));

export const allLessons: Lesson[] = units.flatMap((u) => u.lessons);
export const lessonBySlug = new Map(allLessons.map((l) => [l.slug, l]));
export const unitById = new Map(units.map((u) => [u.id, u]));

export function lessonNeighbours(slug: string) {
  const i = allLessons.findIndex((l) => l.slug === slug);
  return {
    prev: i > 0 ? allLessons[i - 1] : null,
    next: i >= 0 && i < allLessons.length - 1 ? allLessons[i + 1] : null,
    index: i,
  };
}

/** Side quests don't count toward progress. */
export const trackedLessons = allLessons.filter((l) => !l.optional);

/** The lessons that make up one Inventor Lab project. */
export const projectLessons = (letter: string) =>
  allLessons.filter((l) => l.project === letter);

export const stats = {
  lessons: allLessons.length,
  videos: allLessons.filter((l) => l.hasVideo).length,
  units: rawUnits.length - 1,
  capstones: capstones.length,
  sensors: 30,
} as const;`);
writeFileSync(TS, out.join('\n') + '\n');

/* ---------- report ---------------------------------------------------- */
const roster = JSON.parse(readFileSync(ROSTER, 'utf8'));
const n = course.units.reduce((a, u) => a + u.lessons.length, 0);
const stale = roster.students.filter((s) => !s.wrap);
console.log(`\n  Sealed ${n} lessons.`);
console.log(`    public/course.enc.json   ${(JSON.stringify(secret).length / 1024).toFixed(0)} KB encrypted`);
console.log(`    src/data/curriculum.ts   outline only, safe to publish`);
console.log(`  ${roster.students.length - stale.length} login(s) can open it.`);
if (stale.length) console.log(`  ${stale.length} old login(s) cannot — re-issue them.`);
console.log('\n  Next:  git add -A && git commit -m "update course" && git push\n');
