// GENERATED by `npm run seal` from content/course.json — do not edit by hand.
//
// This is the PUBLIC half of the course: the outline. Video URLs, slides, code,
// wiring, materials and learning goals are NOT here — they live encrypted in
// public/course.enc.json and are decrypted in the browser once a student signs in.

import type { Lesson, Unit, Capstone } from '@/lib/types';

const rawUnits: (Omit<Unit, 'lessons'> & { lessons: Omit<Lesson, 'unitId'>[] })[] = [
  {
    id: "unit-0", num: "0", title: "Getting Started", emoji: "📦",
    tagline: "Open the box", blurb: "Unpack the kit, install the software, and figure out how this whole thing works.", accent: "orange",
    lessons: [
      { slug: "0-1a-getting-to-know-your-kit", id: "0.1a", title: "Getting to Know Your Kit", blurb: "Open the box. Meet everything inside. None of it bites.", hasVideo: true, },
      { slug: "0-1b-getting-to-know-your-kit-part-2", id: "0.1b", title: "Getting to Know Your Kit, Part 2", blurb: "A quick look at the fiddly modules. The ones with extra pins and tiny writing on them.", hasVideo: true, },
      { slug: "0-2-how-to-navigate-the-lessons", id: "0.2", title: "How to Navigate the Lessons", blurb: "How this works: watch, wire, run. Plus where the code lives and how to yell for help.", hasVideo: true, },
      { slug: "0-3-downloading-the-arduino-software", id: "0.3", title: "Downloading the Arduino Software", blurb: "Get the free Arduino app onto your computer and plug the board in for the first time.", hasVideo: true, },
    ],
  },
  {
    id: "unit-1", num: "1", title: "Intro to Robotics & Circuits", emoji: "⚡",
    tagline: "Make electricity do things", blurb: "Circuits, breadboards, LEDs, resistors, buttons and buzzers — all before you write a single line of code.", accent: "amber",
    lessons: [
      { slug: "1-1-what-is-a-computer", id: "1.1", title: "What is a Computer?", blurb: "Every computer does three things. Yours does them too, it just doesn't have a screen to brag about it.", hasVideo: true, },
      { slug: "1-2-circuits-and-electricity", id: "1.2", title: "Circuits and Electricity", blurb: "Electricity is lazy. It only moves if you give it a loop to run around.", hasVideo: true, },
      { slug: "1-3-the-breadboard", id: "1.3", title: "The Breadboard", blurb: "There is a secret map of connections hiding inside your breadboard. Here it is.", hasVideo: true, },
      { slug: "1-4-led", id: "1.4", title: "LED", blurb: "Light your first LED. Long leg, short leg, and why backwards gets you nothing.", hasVideo: true, },
      { slug: "1-5-resistors", id: "1.5", title: "Resistors", blurb: "Every LED needs a bodyguard. Meet the resistor, and learn to read its stripes.", hasVideo: true, },
      { slug: "1-6-buttons", id: "1.6", title: "Buttons", blurb: "Add a button and suddenly you are in charge instead of the circuit.", hasVideo: true, },
      { slug: "1-7-the-button-challenge", id: "1.7", title: "The Button Challenge", blurb: "Your first proper challenge. Two buttons, two LEDs, one puzzle, and no code allowed.", hasVideo: false, },
      { slug: "1-8-buzzers", id: "1.8", title: "Buzzers", blurb: "Time to make noise. Two kinds of buzzer, and you can hear the difference.", hasVideo: true, },
      { slug: "1-9-inventor-challenge", id: "1.9", title: "Inventor Challenge", blurb: "End of Unit 1. Take the LEDs, buttons and buzzer and invent something nobody has built before.", hasVideo: false, },
      { slug: "inside-a-computer-chip-factory", id: "★", title: "Inside a Computer Chip Factory", blurb: "Side quest. How the chip on your Arduino actually gets made. It is wild.", hasVideo: true, optional: true, },
    ],
  },
  {
    id: "unit-2", num: "2", title: "Sensors & Interaction", emoji: "🛰️",
    tagline: "Give your robot senses", blurb: "Your first real code, then eleven sensors: light, heat, tilt, water, magnets and more.", accent: "cyan",
    lessons: [
      { slug: "2-1-led-blink", id: "2.1", title: "LED Blink", blurb: "The classic first program. Make a light blink. Then make it blink faster. You are a programmer now.", hasVideo: true, },
      { slug: "2-2-police-siren", id: "2.2", title: "Police Siren", blurb: "Two LEDs, flashing back and forth. It is all in the timing.", hasVideo: true, },
      { slug: "2-3-button-input", id: "2.3", title: "Button Input", blurb: "Teach the Arduino to listen. Press the button, something happens, instantly.", hasVideo: true, },
      { slug: "2-4-light-sensor", id: "2.4", title: "Light Sensor", blurb: "A photoresistor lets your robot see how bright the room is. Not on or off. An actual number.", hasVideo: true, },
      { slug: "2-5-light-switch", id: "2.5", title: "Light Switch", blurb: "Turn that light sensor into a night light that switches itself on when it gets dark.", hasVideo: true, },
      { slug: "2-6-reaction-time-game-part-1", id: "2.6", title: "Reaction Time Game, Part 1", blurb: "Start of the Unit 2 build. Wire the game up and get the light to say GO.", hasVideo: true, },
      { slug: "2-7-reaction-time-game-part-2", id: "2.7", title: "Reaction Time Game, Part 2", blurb: "Now measure how fast you actually are, down to the millisecond.", hasVideo: true, },
      { slug: "2-8-reaction-time-game-part-3", id: "2.8", title: "Reaction Time Game, Part 3", blurb: "Add a high score, catch the cheaters, play a victory sound. Then go beat your friends.", hasVideo: true, },
      { slug: "2-9-rgb-led", id: "2.9", title: "RGB LED", blurb: "One LED. Sixteen million colours. Mix them yourself out of red, green and blue.", hasVideo: true, },
      { slug: "2-10-temperature-and-humidity-sensor", id: "2.10", title: "Temperature and Humidity Sensor", blurb: "Find out how hot the room really is, using a sensor and somebody else's code library.", hasVideo: true, },
      { slug: "2-11-rgb-led-temperature-sensor", id: "2.11", title: "RGB LED + Temperature Sensor", blurb: "Two lessons glued together. The LED goes blue when it is cold and red when it is hot.", hasVideo: true, },
      { slug: "2-12-joystick", id: "2.12", title: "Joystick", blurb: "Two directions and a click. Read a joystick like a game controller.", hasVideo: true, },
      { slug: "2-13-tilt-sensor", id: "2.13", title: "Tilt Sensor", blurb: "A switch that flips when you tip it. Perfect for alarms and secret traps.", hasVideo: true, },
      { slug: "2-14-water-level-sensor", id: "2.14", title: "Water Level Sensor", blurb: "Detect water. Build a rain alarm, or a plant that tells you it is thirsty.", hasVideo: true, },
      { slug: "2-15-magnetic-sensor", id: "2.15", title: "Magnetic Sensor", blurb: "Sense a magnet straight through a wall. It is the trick behind every door alarm.", hasVideo: true, },
    ],
  },
  {
    id: "unit-3", num: "3", title: "Motors & Movement", emoji: "⚙️",
    tagline: "Make it move", blurb: "DC motors, servos and an H-bridge, ending with a knob that controls a real spinning motor.", accent: "lime",
    lessons: [
      { slug: "3-1-intro-to-motors", id: "3.1", title: "Intro to Motors", blurb: "Electricity that moves things. Meet DC motors and servos, and find out why motors need their own power.", hasVideo: true, },
      { slug: "3-2-dc-motor", id: "3.2", title: "DC Motor", blurb: "Spin a real motor with an H-bridge. Forwards, backwards, stop.", hasVideo: true, },
      { slug: "3-3-servo-motor", id: "3.3", title: "Servo Motor", blurb: "A motor that goes to an exact angle and stays put. This is the muscle behind arms and turrets.", hasVideo: true, },
      { slug: "3-4-rotary-encoder", id: "3.4", title: "Rotary Encoder", blurb: "Wire a knob to a motor. Twist it and the wheel speeds up. Twist back and it slows down.", hasVideo: true, },
      { slug: "how-rotary-encoders-work", id: "★", title: "How Rotary Encoders Work", blurb: "Side quest. Sixty seconds on the clever pattern hiding inside the knob.", hasVideo: true, optional: true, },
    ],
  },
  {
    id: "unit-4", num: "4", title: "Displays & Communication", emoji: "📺",
    tagline: "Make it talk back", blurb: "LCD and OLED screens, your own pixel art, a live sensor dashboard, and typing commands to your board.", accent: "violet",
    lessons: [
      { slug: "4-1-what-are-displays", id: "4.1", title: "What are Displays?", blurb: "Pixels, characters and segments. All the ways a machine can show you something.", hasVideo: true, },
      { slug: "4-2-lcd-screen", id: "4.2", title: "LCD Screen", blurb: "Put your own words on a real screen. The classic 16x2 LCD, wired up and working.", hasVideo: true, },
      { slug: "4-3-custom-characters", id: "4.3", title: "Custom Characters", blurb: "Draw your own tiny 5x8 pictures. Hearts, faces, whatever you want, and print them.", hasVideo: true, },
      { slug: "4-4-oled-screen", id: "4.4", title: "OLED Screen", blurb: "Upgrade to a crisp pixel display. Two wires and it glows.", hasVideo: true, },
      { slug: "4-5-drawing-shapes", id: "4.5", title: "Drawing Shapes", blurb: "Lines, circles, rectangles. Then make them move and you have a tiny game screen.", hasVideo: true, },
      { slug: "4-6-temperature-dashboard", id: "4.6", title: "Temperature Dashboard", blurb: "A live dashboard on the OLED showing temperature and humidity, with a graph that scrolls.", hasVideo: true, },
      { slug: "4-7-serial-input", id: "4.7", title: "Serial Input", blurb: "Talk to your Arduino. Type commands from your computer and watch it obey.", hasVideo: true, },
    ],
  },
  {
    id: "unit-5", num: "5", title: "Inventor Lab", emoji: "🚀",
    tagline: "Build the big ones", blurb: "The five big builds. Everything from the earlier units, put to work on something you get to keep.", accent: "pink",
    lessons: [
      { slug: "5-1-welcome-to-the-inventor-lab", id: "5.1", title: "Welcome to the Inventor Lab", blurb: "How the big projects work, what you need for each, and which one to build first.", hasVideo: true, },
      { slug: "5a-1-rc-car-assembling-the-chassis", id: "5A.1", title: "RC Car: Assembling the Chassis", blurb: "Screws, wheels, motors, frame. Build the body before it can drive anywhere.", hasVideo: true, project: "A", },
      { slug: "5a-2-rc-car-wiring", id: "5A.2", title: "RC Car: Wiring", blurb: "Get both motors talking to the L298N, and give them power that is not your Arduino.", hasVideo: true, project: "A", },
      { slug: "5a-3-rc-car-coding", id: "5A.3", title: "RC Car: Coding", blurb: "Make it drive. Forwards, backwards, turns, and then tune out the wobble.", hasVideo: true, project: "A", },
      { slug: "5b-1-tic-tac-toe-wiring", id: "5B.1", title: "Tic-Tac-Toe: Wiring", blurb: "Lay out the board. This is the biggest wiring job so far, so take it slow.", hasVideo: true, project: "B", },
      { slug: "5b-2-tic-tac-toe-drawing-the-board", id: "5B.2", title: "Tic-Tac-Toe: Drawing the Board", blurb: "Get the grid showing up properly before you worry about the game.", hasVideo: true, project: "B", },
      { slug: "5b-3-tic-tac-toe-placing-the-marks", id: "5B.3", title: "Tic-Tac-Toe: Placing the Marks", blurb: "Pick a square, place your mark. It starts to feel like a game.", hasVideo: true, project: "B", },
      { slug: "5b-4-tic-tac-toe-two-player-tic-tac-toe", id: "5B.4", title: "Tic-Tac-Toe: Two Player Tic-Tac-Toe", blurb: "Take turns, spot the winner, handle a draw. Now go grab a friend.", hasVideo: true, project: "B", },
      { slug: "5b-5-tic-tac-toe-one-player-tic-tac-toe", id: "5B.5", title: "Tic-Tac-Toe: One Player Tic-Tac-Toe", blurb: "Write the opponent. Teach it to block you, then teach it to be really annoying.", hasVideo: true, project: "B", },
    ],
  },
  {
    id: "extras", num: "★", title: "Extras", emoji: "🧰",
    tagline: "When something breaks", blurb: "Troubleshooting, and the weekly session where I help you unbreak it.", accent: "slate",
    lessons: [
      { slug: "troubleshooting", id: "T", title: "Troubleshooting", blurb: "Nothing lighting up? Code will not upload? Start here. These are the problems everybody hits.", hasVideo: true, },
      { slug: "live-help-sessions", id: "★", title: "Live Help Sessions", blurb: "Every week I run an online session. Bring whatever you're stuck on and we'll fix it together.", hasVideo: false, },
    ],
  },
];

export const capstones: Capstone[] = [
  { letter: "A", name: "RC Car", blurb: "Build a two-wheel-drive car from a bare chassis, then drive it around your house.", skills: ["DC motors","L298N H-bridge","Chassis build","Speed control"], lessonCount: 3 },
  { letter: "B", name: "Tic-Tac-Toe", blurb: "An LED board, buttons, and an opponent you wrote yourself.", skills: ["Arrays & game state","Win detection","Simple AI","Big-board wiring"], lessonCount: 5 },
  { letter: "C", name: "Laser Harp", blurb: "Invisible strings made of light. Wave your hand through a beam and it plays a note.", skills: ["Lasers & photoresistors","Calibration","Tone generation"], lessonCount: 0 },
  { letter: "D", name: "Crack the Vault", blurb: "A keypad-locked vault with a servo bolt, an alarm, and a combination only you know.", skills: ["Keypad input","Servo lock","State machines"], lessonCount: 0 },
  { letter: "E", name: "Sentry Turret", blurb: "A pan-tilt turret that scans the room, locks onto a target and fires.", skills: ["Pan-tilt servos","Ultrasonic ranging","Target tracking"], lessonCount: 0 },
];

export const units: Unit[] = rawUnits.map((u) => ({
  ...u,
  lessons: u.lessons.map((l) => ({ ...l, unitId: u.id })),
}));

export const allLessons: Lesson[] = units.flatMap((u) => u.lessons);
export const lessonBySlug = new Map(allLessons.map((l) => [l.slug, l]));
export const unitById = new Map(units.map((u) => [u.id, u]));

export function lessonNeighbours(slug: string) {
  const i = allLessons.findIndex((l) => l.slug === slug);
  return {
    prev: i > 0 ? allLessons[i - 1] : null,
    next: i >= 0 && i < allLessons.length - 1 ? allLessons[i + 1] : null,
    index: i,
  };
}

/** Side quests don't count toward progress. */
export const trackedLessons = allLessons.filter((l) => !l.optional);

/** The lessons that make up one Inventor Lab project. */
export const projectLessons = (letter: string) =>
  allLessons.filter((l) => l.project === letter);

export const stats = {
  lessons: allLessons.length,
  videos: allLessons.filter((l) => l.hasVideo).length,
  units: rawUnits.length - 1,
  capstones: capstones.length,
  sensors: 30,
} as const;
